version: '3.8'

services:
  backend:
    build: .
    command: python /project/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/project
    ports:
    - 8000:8000
    depends_on:
      - db
  db:
    image: 'postgres:11'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    volumes:
    - postgres_data:/var/lib/postgres/data/
volumes:
  postgres_data: